"""Heuristic signals for detecting low-effort 'AI slop' repositories.

Each signal is a pure function: it takes a ``repo`` dict and returns
``(points, reason)``. ``points`` is a non-negative float up to the signal's
declared ``max_points``; ``reason`` is a short human-readable string explaining
why points were awarded, or ``None`` when the signal does not fire.

The ``repo`` dict is the GitHub search result for a repo, optionally enriched
with these extra keys (all optional; signals degrade gracefully if missing):

    readme              str   - decoded README text
    file_paths          list  - repo file paths (from the git tree)
    code_samples        list  - raw contents of a few sampled source files
    commits_count       int   - number of commits
    contributors_count  int   - number of contributors

Signals never raise on missing data — a missing input just yields (0, None).
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from typing import Callable, List, Optional, Tuple

Signal = Callable[[dict], Tuple[float, Optional[str]]]

# --- emoji detection ---------------------------------------------------------

# Covers the common emoji blocks: emoticons, symbols & pictographs, transport,
# supplemental symbols, dingbats, and misc symbols. Not exhaustive but catches
# the vast majority of emoji used in real repos.
EMOJI_PATTERN = re.compile(
    "["
    "\U0001F300-\U0001FAFF"  # symbols & pictographs, supplemental, etc.
    "\U00002600-\U000027BF"  # misc symbols + dingbats
    "\U0001F1E6-\U0001F1FF"  # regional indicators (flags)
    "\U00002190-\U000021FF"  # arrows (often decorative in AI readmes)
    "\U0000FE00-\U0000FE0F"  # variation selectors
    "\U00002B00-\U00002BFF"  # misc symbols and arrows (stars, etc.)
    "]"
)


def count_emoji(text: str) -> int:
    if not text:
        return 0
    return len(EMOJI_PATTERN.findall(text))


def _parse_dt(value: Optional[str]) -> Optional[datetime]:
    if not value:
        return None
    try:
        return datetime.fromisoformat(value.replace("Z", "+00:00"))
    except (ValueError, AttributeError):
        return None


# Names that signal zero naming effort.
_DEFAULT_NAMES = {
    "test", "test-repo", "testing", "untitled", "untitled-1", "my-project",
    "myproject", "new-project", "newproject", "project", "demo", "example",
    "sample", "hello-world", "helloworld", "temp", "tmp", "foo", "bar",
    "app", "myapp", "my-app", "repo", "code", "main",
}

# Phrases that strongly suggest AI-generated boilerplate prose.
_AI_PHRASES = [
    "as an ai language model",
    "as a large language model",
    "i cannot fulfill this request",
    "this project was generated",
    "this readme was generated",
    "generated by chatgpt",
    "generated with the help of ai",
    "in conclusion,",
    "in today's fast-paced world",
    "in the ever-evolving world",
    "in the world of",
    "certainly! here",
    "sure! here's",
    "here is a comprehensive",
    "this comprehensive guide",
    "unleash the power",
    "harness the power",
    "elevate your",
    "seamlessly integrate",
    "revolutionize the way",
    "a game-changer",
    "delve into",
]

_PLACEHOLDERS = [
    "lorem ipsum",
    "<your-name-here>",
    "your-name-here",
    "your_project_name",
    "yourusername",
    "your-username",
    "todo: add",
    "tbd",
    "coming soon",
    "work in progress",
    "replace this with",
    "insert your",
]

_CODE_EXTS = (
    ".py", ".js", ".ts", ".jsx", ".tsx", ".java", ".go", ".rb", ".php",
    ".c", ".cpp", ".cs", ".rs", ".swift", ".kt", ".sh",
)

# ---------------------------------------------------------------------------
# Group 1: repo metadata
# ---------------------------------------------------------------------------

def sig_zero_stars(repo: dict) -> Tuple[float, Optional[str]]:
    if repo.get("stargazers_count", 0) == 0:
        return 5.0, "0 stars"
    return 0.0, None


def sig_zero_forks(repo: dict) -> Tuple[float, Optional[str]]:
    if repo.get("forks_count", 0) == 0:
        return 3.0, "0 forks"
    return 0.0, None


def sig_no_description(repo: dict) -> Tuple[float, Optional[str]]:
    desc = (repo.get("description") or "").strip()
    if not desc:
        return 5.0, "no description"
    return 0.0, None


def sig_no_license(repo: dict) -> Tuple[float, Optional[str]]:
    if not repo.get("license"):
        return 4.0, "no license"
    return 0.0, None


def sig_default_name(repo: dict) -> Tuple[float, Optional[str]]:
    name = (repo.get("name") or "").strip().lower()
    if name in _DEFAULT_NAMES:
        return 5.0, f"low-effort name '{name}'"
    # names like "project-1", "test123", "untitled (1)"
    if re.fullmatch(r"(test|temp|project|untitled|demo|app)[-_ ]?\d*", name):
        return 5.0, f"low-effort name '{name}'"
    return 0.0, None


def sig_brand_new(repo: dict) -> Tuple[float, Optional[str]]:
    created = _parse_dt(repo.get("created_at"))
    pushed = _parse_dt(repo.get("pushed_at"))
    if created and pushed:
        age_days = (pushed - created).total_seconds() / 86400.0
        if age_days <= 1.0:
            return 3.0, "created and last pushed within one day"
    return 0.0, None


# ---------------------------------------------------------------------------
# Group 2: README quality
# ---------------------------------------------------------------------------

def sig_ai_boilerplate(repo: dict) -> Tuple[float, Optional[str]]:
    readme = (repo.get("readme") or "").lower()
    if not readme:
        return 0.0, None
    hits = [p for p in _AI_PHRASES if p in readme]
    if not hits:
        return 0.0, None
    points = min(10.0, 4.0 + 3.0 * len(hits))
    sample = ", ".join(f'"{h}"' for h in hits[:2])
    return points, f"AI-boilerplate phrasing ({sample})"


def sig_emoji_headers(repo: dict) -> Tuple[float, Optional[str]]:
    readme = repo.get("readme")
    if not readme:
        return 0.0, None
    header_lines = [ln for ln in readme.splitlines() if ln.lstrip().startswith("#")]
    if not header_lines:
        return 0.0, None
    emoji_headers = sum(1 for ln in header_lines if count_emoji(ln) > 0)
    ratio = emoji_headers / len(header_lines)
    if emoji_headers >= 3 and ratio >= 0.5:
        return 6.0, f"{emoji_headers} of {len(header_lines)} headers stuffed with emoji"
    if emoji_headers >= 2:
        return 3.0, f"{emoji_headers} emoji-stuffed headers"
    return 0.0, None


def sig_placeholder_text(repo: dict) -> Tuple[float, Optional[str]]:
    readme = (repo.get("readme") or "").lower()
    if not readme:
        return 0.0, None
    hits = [p for p in _PLACEHOLDERS if p in readme]
    if hits:
        return 5.0, f"placeholder text ({hits[0]!r})"
    return 0.0, None


def sig_readme_only(repo: dict) -> Tuple[float, Optional[str]]:
    paths = repo.get("file_paths")
    if not paths:
        return 0.0, None
    code_files = [p for p in paths if p.lower().endswith(_CODE_EXTS)]
    if len(code_files) == 0 and any("readme" in p.lower() for p in paths):
        return 4.0, "README but essentially no code"
    return 0.0, None


# ---------------------------------------------------------------------------
# Group 3: code / commit effort
# ---------------------------------------------------------------------------

def sig_single_commit(repo: dict) -> Tuple[float, Optional[str]]:
    n = repo.get("commits_count")
    if n is None:
        return 0.0, None
    if n <= 1:
        return 8.0, "single commit (one-shot dump)"
    if n <= 3:
        return 4.0, f"only {n} commits"
    return 0.0, None


def sig_no_tests(repo: dict) -> Tuple[float, Optional[str]]:
    paths = repo.get("file_paths")
    if not paths:
        return 0.0, None
    has_tests = any(
        ("test" in p.lower() or "spec" in p.lower()) and p.lower().endswith(_CODE_EXTS)
        for p in paths
    )
    if not has_tests:
        return 4.0, "no tests"
    return 0.0, None


def sig_no_ci(repo: dict) -> Tuple[float, Optional[str]]:
    paths = repo.get("file_paths")
    if not paths:
        return 0.0, None
    has_ci = any(
        ".github/workflows" in p or p.endswith((".travis.yml", ".gitlab-ci.yml"))
        or "circleci" in p.lower()
        for p in paths
    )
    if not has_ci:
        return 4.0, "no CI configuration"
    return 0.0, None


def sig_few_files(repo: dict) -> Tuple[float, Optional[str]]:
    paths = repo.get("file_paths")
    if not paths:
        return 0.0, None
    code_files = [p for p in paths if p.lower().endswith(_CODE_EXTS)]
    if len(code_files) <= 2:
        return 4.0, f"only {len(code_files)} source file(s)"
    return 0.0, None


# ---------------------------------------------------------------------------
# Group 4: activity
# ---------------------------------------------------------------------------

def sig_zero_issues(repo: dict) -> Tuple[float, Optional[str]]:
    # open_issues_count includes PRs; treat zero as a sign of no engagement.
    if repo.get("open_issues_count", 0) == 0:
        return 4.0, "no open issues/PRs"
    return 0.0, None


def sig_single_contributor(repo: dict) -> Tuple[float, Optional[str]]:
    n = repo.get("contributors_count")
    if n is None:
        return 0.0, None
    if n <= 1:
        return 4.0, "only the owner ever contributed"
    return 0.0, None


def sig_no_activity_after_creation(repo: dict) -> Tuple[float, Optional[str]]:
    created = _parse_dt(repo.get("created_at"))
    pushed = _parse_dt(repo.get("pushed_at"))
    if created and pushed:
        age_days = (pushed - created).total_seconds() / 86400.0
        if age_days <= 1.0:
            return 3.0, "no pushes after creation day"
    return 0.0, None


def sig_abandoned(repo: dict) -> Tuple[float, Optional[str]]:
    pushed = _parse_dt(repo.get("pushed_at"))
    if not pushed:
        return 0.0, None
    now = datetime.now(timezone.utc)
    idle_days = (now - pushed).total_seconds() / 86400.0
    if idle_days >= 180:
        return 4.0, f"untouched for {int(idle_days)} days"
    return 0.0, None


# ---------------------------------------------------------------------------
# Group 5: emojis in code
# ---------------------------------------------------------------------------

def sig_emoji_in_code(repo: dict) -> Tuple[float, Optional[str]]:
    samples = repo.get("code_samples")
    if not samples:
        return 0.0, None
    total_emoji = 0
    files_with_emoji = 0
    for content in samples:
        n = count_emoji(content)
        if n > 0:
            files_with_emoji += 1
            total_emoji += n
    if total_emoji == 0:
        return 0.0, None
    # Scale: a couple emoji is mild; lots across files is a strong tell.
    points = min(15.0, 3.0 * files_with_emoji + 1.0 * total_emoji)
    return points, f"{total_emoji} emoji inside code across {files_with_emoji} file(s)"


# ---------------------------------------------------------------------------
# Registry — grouped, each entry carries its max for normalization.
# ---------------------------------------------------------------------------

GROUPS: dict = {
    "metadata": [
        (sig_zero_stars, 5.0),
        (sig_zero_forks, 3.0),
        (sig_no_description, 5.0),
        (sig_no_license, 4.0),
        (sig_default_name, 5.0),
        (sig_brand_new, 3.0),
    ],
    "readme": [
        (sig_ai_boilerplate, 10.0),
        (sig_emoji_headers, 6.0),
        (sig_placeholder_text, 5.0),
        (sig_readme_only, 4.0),
    ],
    "effort": [
        (sig_single_commit, 8.0),
        (sig_no_tests, 4.0),
        (sig_no_ci, 4.0),
        (sig_few_files, 4.0),
    ],
    "activity": [
        (sig_zero_issues, 4.0),
        (sig_single_contributor, 4.0),
        (sig_no_activity_after_creation, 3.0),
        (sig_abandoned, 4.0),
    ],
    "emoji_code": [
        (sig_emoji_in_code, 15.0),
    ],
}


def all_signals() -> List[Tuple[Signal, float]]:
    out: List[Tuple[Signal, float]] = []
    for entries in GROUPS.values():
        out.extend(entries)
    return out


# Theoretical maximum raw points if every signal fired at its cap.
MAX_RAW = sum(cap for _, cap in all_signals())
